### ISSUE TITLE
Support TableOfContents

### ISSUE THREAD

**Issue by mrcasals** [siegerts/hugo-theme-basic#1]
Hi!

Could you add support for `TableOfContents` in posts?

Thank you! 😄

**Comment by siegerts** [comment]
Hi @mrcasals!

The `.TableOfContents` built-in can be used right in your `*.md` files with a quick [shortcode](https://gohugo.io/content-management/shortcodes/) in _your_ project directory.

```html
<!-- layouts/shortcodes/toc.html -->
{{ replace .Page.TableOfContents `href="#` (printf `href="%s#` .Page.Permalink) | safeHTML }}
```
Then reference in your files with `{{< toc >}}`.  The above outputs HTML in the form of `<nav id="TableOfContents">`. This can be styled with a custom css file.

Something like below should get it to a good starting point within the context of the theme:

```css
nav#TableOfContents {
  width: 90%;
  margin-top: 1rem;
  margin-bottom: 1rem;
}

nav#TableOfContents ul {
  line-height: 1.5;
  list-style-type: none;
  text-decoration: none;
  padding-left: 0.5rem;
}

nav#TableOfContents ul a {
  /* link color */
  color: #000;
  text-decoration: none;
  transition: color 0.15s ease-in;
}

nav#TableOfContents ul a:hover,
nav#TableOfContents ul a:focus {
  text-decoration: underline;
}

```

I'd rather not make too many structural changes to the default layouts.  This way, it's a bit more flexible and you can place and style the generated table any way that you'd like.
